[PK]
CL=THETA_CL*exp(ETA_CL)
V1=THETA_V1*exp(ETA_V1)
V2=THETA_V2
Q=THETA_Q
S1=V1

[DES]
d/dt(A_CENTRAL)=Q*A_PERIPHERAL/V2 + (-CL/V1 - Q/V1)*A_CENTRAL
d/dt(A_PERIPHERAL)=-Q*A_PERIPHERAL/V2 + Q*A_CENTRAL/V1
d/dt(A_OUTPUT)=CL*A_CENTRAL/V1
F=A_CENTRAL/S1
dur(A_CENTRAL)=5

[ERROR]
CP=F
OBS_CP=CP*(EPS_PROP + 1)
Y=OBS_CP

