# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, develop, snake_case]
  pull_request:
    branches: [main, develop, snake_case]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          # - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
          - {os: ubuntu-latest,   r: 'release'}
          # - {os: ubuntu-latest,   r: 'oldrel-1'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
  
  # New dedicated job to check against BLIS
  R-CMD-check-BLIS:
    runs-on: ubuntu-latest
    container:
      image: fedora:44
    steps:
      - name: Install system dependencies & BLIS
        run: |
          dnf install -y \
            R-devel \
            gcc \
            gcc-gfortran \
            blis-devel \
            flexiblas-blis-serial \
            libcurl-devel \
            openssl-devel \
            libxml2-devel \
            git

      - name: Force R to use BLIS
        run: |
          BLIS_PATH=$(ldconfig -p | grep libblis.so | awk '{print $NF}' | head -n 1)
          R_LIB_DIR=$(R RHOME)/lib
          echo "Found BLIS at: $BLIS_PATH"
          echo "Overwriting R's libRblas.so in: $R_LIB_DIR"
          cp -f "$BLIS_PATH" "$R_LIB_DIR/libRblas.so"

      - uses: actions/checkout@v3

      - name: Verify Active BLAS Backend
        run: |
          Rscript -e 'cat("Active BLAS:", sessionInfo()$BLAS, "\n")'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
        env:
          LD_PRELOAD: /usr/lib64/libblis.so
        with:
          upload-snapshots: true
